'use strict';

// Declare app level module
angular.module('particle', [
  'particle.common',
  'particle.pages',
  'particle.templates' // dynamically generated by grunt-angular-templates
]);

angular.module('particle')

  .config(function ($locationProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/');

    // enable the HTML5 push/pop history API
    // if enabled make sure the on the server side everything is pushed to the index page
    // otherwise deep linking will not work properly
    // $locationProvider.html5Mode(true);
  })

  .run(function ($rootScope, $state, $stateParams) {
    $rootScope.$state = $state;
    $rootScope.$stateParams = $stateParams;
    // $rootScope.$on('$stateChangeSuccess', function () {
    //   console.log('==================== $stateChangeSuccess =========================');
    // });

    // $rootScope.$on('$locationChangeSuccess', function () {
    //   console.log('==================== $locationChangeSuccess =========================');
    // });
  });

// This module will be used by grunt-angular-templates to add all templates to cache
angular.module('particle.templates', ['wu.masonry']);